airflow:
  dag_id: "dbt_snowflake_dag"
  owner: "airflow"
  start_date: "2025-01-01"
schedule_interval: "0 0 * * *" # daily at midnight

dbt:
  project_dir: "/path/to/dbt/project"
  profiles_dir: "/path/to/dbt/profiles"

snowflake:
  account: "your_account"
  warehouse: "your_warehouse"
  role: "your_role"
  schema: "your_schema"
